source 'https://github.com/CocoaPods/Specs.git'

target 'M2DWebViewController', :exclusive => true do
  pod "M2DWebViewController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "M2DWebViewController", :path => "../"

  pod 'Kiwi'
end
