source 'https://github.com/CocoaPods/Specs.git'

target 'M2DWebViewController' do
  pod "M2DWebViewController", :path => "../"
  
  target 'Tests' do
    pod "M2DWebViewController", :path => "../"
  
    pod 'Kiwi'
  end  
end